# Generated by Django 3.1.2 on 2020-10-26 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import touchbase.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='touchbase.group')),
            ],
        ),
        migrations.CreateModel(
            name='Truancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject', models.IntegerField(choices=[(0, 'HOMEROOM'), (1, 'ELA'), (2, 'MATH'), (3, 'CIVICS'), (4, 'SCIENCE'), (5, 'ESL'), (6, 'NUMERACY')], null=True)),
                ('issue', models.IntegerField(choices=[(0, 'ABSENT'), (1, 'TARDY'), (2, 'SKIP')], default=touchbase.utils.TruancyTypes['ABSENT'])),
                ('discussed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touchbase.student')),
            ],
            options={
                'verbose_name': 'Truancy',
                'verbose_name_plural': 'Truancies',
            },
        ),
        migrations.CreateModel(
            name='MissingWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject', models.IntegerField(choices=[(0, 'HOMEROOM'), (1, 'ELA'), (2, 'MATH'), (3, 'CIVICS'), (4, 'SCIENCE'), (5, 'ESL'), (6, 'NUMERACY')], default=touchbase.utils.SubjectTypes['HOMEROOM'])),
                ('count', models.IntegerField(default=1)),
                ('discussed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touchbase.student')),
            ],
            options={
                'verbose_name': 'Missing Work',
                'verbose_name_plural': 'Missing Assignments',
            },
        ),
    ]
