# Generated by Django 3.1.2 on 2020-11-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchbase', '0003_auto_20201101_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_reports', 'Can view reports'),)},
        ),
    ]
